
#define GLAPI

#include "bbopengl.h"

#include <stdio.h>

void *SDL_GL_GetProcAddress( const char *proc );

int SDL_GL_ExtensionSupported( const char *ext );

int SDL_GL_GetAttribute( int attr,int *value );

#if __EMSCRIPTEN__

void GLAPIENTRY glClearDepthf( GLclampf depth );

void GLAPIENTRY bbglClearDepth( GLclampd depth ){

	glClearDepthf( (GLclampf)depth );
}

#else

#define SDL_GL_CONTEXT_PROFILE_MASK		21
#define SDL_GL_CONTEXT_PROFILE_ES		0x0004 

void (GLAPIENTRY*bbglClearDepthf)( GLclampf depth );

void GLAPIENTRY bbglClearDepthd( GLclampd depth ){

	bbglClearDepthf( (GLclampf)depth );
}

#endif

void bbglInit(){

#if __EMSCRIPTEN__

	BBGL_ES=1;

	BBGL_draw_buffers=SDL_GL_ExtensionSupported( "GL_WEBGL_draw_buffers" );
		
#else

	bbglAccum=SDL_GL_GetProcAddress("glAccum");
	bbglAlphaFunc=SDL_GL_GetProcAddress("glAlphaFunc");
	bbglAreTexturesResident=SDL_GL_GetProcAddress("glAreTexturesResident");
	bbglArrayElement=SDL_GL_GetProcAddress("glArrayElement");
	bbglBegin=SDL_GL_GetProcAddress("glBegin");
	bbglBindTexture=SDL_GL_GetProcAddress("glBindTexture");
	bbglBitmap=SDL_GL_GetProcAddress("glBitmap");
	bbglBlendFunc=SDL_GL_GetProcAddress("glBlendFunc");
	bbglCallList=SDL_GL_GetProcAddress("glCallList");
	bbglCallLists=SDL_GL_GetProcAddress("glCallLists");
	bbglClear=SDL_GL_GetProcAddress("glClear");
	bbglClearAccum=SDL_GL_GetProcAddress("glClearAccum");
	bbglClearColor=SDL_GL_GetProcAddress("glClearColor");
	bbglClearDepth=SDL_GL_GetProcAddress("glClearDepth");
	bbglClearIndex=SDL_GL_GetProcAddress("glClearIndex");
	bbglClearStencil=SDL_GL_GetProcAddress("glClearStencil");
	bbglClipPlane=SDL_GL_GetProcAddress("glClipPlane");
	bbglColor3b=SDL_GL_GetProcAddress("glColor3b");
	bbglColor3bv=SDL_GL_GetProcAddress("glColor3bv");
	bbglColor3d=SDL_GL_GetProcAddress("glColor3d");
	bbglColor3dv=SDL_GL_GetProcAddress("glColor3dv");
	bbglColor3f=SDL_GL_GetProcAddress("glColor3f");
	bbglColor3fv=SDL_GL_GetProcAddress("glColor3fv");
	bbglColor3i=SDL_GL_GetProcAddress("glColor3i");
	bbglColor3iv=SDL_GL_GetProcAddress("glColor3iv");
	bbglColor3s=SDL_GL_GetProcAddress("glColor3s");
	bbglColor3sv=SDL_GL_GetProcAddress("glColor3sv");
	bbglColor3ub=SDL_GL_GetProcAddress("glColor3ub");
	bbglColor3ubv=SDL_GL_GetProcAddress("glColor3ubv");
	bbglColor3ui=SDL_GL_GetProcAddress("glColor3ui");
	bbglColor3uiv=SDL_GL_GetProcAddress("glColor3uiv");
	bbglColor3us=SDL_GL_GetProcAddress("glColor3us");
	bbglColor3usv=SDL_GL_GetProcAddress("glColor3usv");
	bbglColor4b=SDL_GL_GetProcAddress("glColor4b");
	bbglColor4bv=SDL_GL_GetProcAddress("glColor4bv");
	bbglColor4d=SDL_GL_GetProcAddress("glColor4d");
	bbglColor4dv=SDL_GL_GetProcAddress("glColor4dv");
	bbglColor4f=SDL_GL_GetProcAddress("glColor4f");
	bbglColor4fv=SDL_GL_GetProcAddress("glColor4fv");
	bbglColor4i=SDL_GL_GetProcAddress("glColor4i");
	bbglColor4iv=SDL_GL_GetProcAddress("glColor4iv");
	bbglColor4s=SDL_GL_GetProcAddress("glColor4s");
	bbglColor4sv=SDL_GL_GetProcAddress("glColor4sv");
	bbglColor4ub=SDL_GL_GetProcAddress("glColor4ub");
	bbglColor4ubv=SDL_GL_GetProcAddress("glColor4ubv");
	bbglColor4ui=SDL_GL_GetProcAddress("glColor4ui");
	bbglColor4uiv=SDL_GL_GetProcAddress("glColor4uiv");
	bbglColor4us=SDL_GL_GetProcAddress("glColor4us");
	bbglColor4usv=SDL_GL_GetProcAddress("glColor4usv");
	bbglColorMask=SDL_GL_GetProcAddress("glColorMask");
	bbglColorMaterial=SDL_GL_GetProcAddress("glColorMaterial");
	bbglColorPointer=SDL_GL_GetProcAddress("glColorPointer");
	bbglCopyPixels=SDL_GL_GetProcAddress("glCopyPixels");
	bbglCopyTexImage1D=SDL_GL_GetProcAddress("glCopyTexImage1D");
	bbglCopyTexImage2D=SDL_GL_GetProcAddress("glCopyTexImage2D");
	bbglCopyTexSubImage1D=SDL_GL_GetProcAddress("glCopyTexSubImage1D");
	bbglCopyTexSubImage2D=SDL_GL_GetProcAddress("glCopyTexSubImage2D");
	bbglCullFace=SDL_GL_GetProcAddress("glCullFace");
	bbglDeleteLists=SDL_GL_GetProcAddress("glDeleteLists");
	bbglDeleteTextures=SDL_GL_GetProcAddress("glDeleteTextures");
	bbglDepthFunc=SDL_GL_GetProcAddress("glDepthFunc");
	bbglDepthMask=SDL_GL_GetProcAddress("glDepthMask");
	bbglDepthRange=SDL_GL_GetProcAddress("glDepthRange");
	bbglDisable=SDL_GL_GetProcAddress("glDisable");
	bbglDisableClientState=SDL_GL_GetProcAddress("glDisableClientState");
	bbglDrawArrays=SDL_GL_GetProcAddress("glDrawArrays");
	bbglDrawBuffer=SDL_GL_GetProcAddress("glDrawBuffer");
	bbglDrawElements=SDL_GL_GetProcAddress("glDrawElements");
	bbglDrawPixels=SDL_GL_GetProcAddress("glDrawPixels");
	bbglEdgeFlag=SDL_GL_GetProcAddress("glEdgeFlag");
	bbglEdgeFlagPointer=SDL_GL_GetProcAddress("glEdgeFlagPointer");
	bbglEdgeFlagv=SDL_GL_GetProcAddress("glEdgeFlagv");
	bbglEnable=SDL_GL_GetProcAddress("glEnable");
	bbglEnableClientState=SDL_GL_GetProcAddress("glEnableClientState");
	bbglEnd=SDL_GL_GetProcAddress("glEnd");
	bbglEndList=SDL_GL_GetProcAddress("glEndList");
	bbglEvalCoord1d=SDL_GL_GetProcAddress("glEvalCoord1d");
	bbglEvalCoord1dv=SDL_GL_GetProcAddress("glEvalCoord1dv");
	bbglEvalCoord1f=SDL_GL_GetProcAddress("glEvalCoord1f");
	bbglEvalCoord1fv=SDL_GL_GetProcAddress("glEvalCoord1fv");
	bbglEvalCoord2d=SDL_GL_GetProcAddress("glEvalCoord2d");
	bbglEvalCoord2dv=SDL_GL_GetProcAddress("glEvalCoord2dv");
	bbglEvalCoord2f=SDL_GL_GetProcAddress("glEvalCoord2f");
	bbglEvalCoord2fv=SDL_GL_GetProcAddress("glEvalCoord2fv");
	bbglEvalMesh1=SDL_GL_GetProcAddress("glEvalMesh1");
	bbglEvalMesh2=SDL_GL_GetProcAddress("glEvalMesh2");
	bbglEvalPoint1=SDL_GL_GetProcAddress("glEvalPoint1");
	bbglEvalPoint2=SDL_GL_GetProcAddress("glEvalPoint2");
	bbglFeedbackBuffer=SDL_GL_GetProcAddress("glFeedbackBuffer");
	bbglFinish=SDL_GL_GetProcAddress("glFinish");
	bbglFlush=SDL_GL_GetProcAddress("glFlush");
	bbglFogf=SDL_GL_GetProcAddress("glFogf");
	bbglFogfv=SDL_GL_GetProcAddress("glFogfv");
	bbglFogi=SDL_GL_GetProcAddress("glFogi");
	bbglFogiv=SDL_GL_GetProcAddress("glFogiv");
	bbglFrontFace=SDL_GL_GetProcAddress("glFrontFace");
	bbglFrustum=SDL_GL_GetProcAddress("glFrustum");
	bbglGenLists=SDL_GL_GetProcAddress("glGenLists");
	bbglGenTextures=SDL_GL_GetProcAddress("glGenTextures");
	bbglGetBooleanv=SDL_GL_GetProcAddress("glGetBooleanv");
	bbglGetClipPlane=SDL_GL_GetProcAddress("glGetClipPlane");
	bbglGetDoublev=SDL_GL_GetProcAddress("glGetDoublev");
	bbglGetError=SDL_GL_GetProcAddress("glGetError");
	bbglGetFloatv=SDL_GL_GetProcAddress("glGetFloatv");
	bbglGetIntegerv=SDL_GL_GetProcAddress("glGetIntegerv");
	bbglGetLightfv=SDL_GL_GetProcAddress("glGetLightfv");
	bbglGetLightiv=SDL_GL_GetProcAddress("glGetLightiv");
	bbglGetMapdv=SDL_GL_GetProcAddress("glGetMapdv");
	bbglGetMapfv=SDL_GL_GetProcAddress("glGetMapfv");
	bbglGetMapiv=SDL_GL_GetProcAddress("glGetMapiv");
	bbglGetMaterialfv=SDL_GL_GetProcAddress("glGetMaterialfv");
	bbglGetMaterialiv=SDL_GL_GetProcAddress("glGetMaterialiv");
	bbglGetPixelMapfv=SDL_GL_GetProcAddress("glGetPixelMapfv");
	bbglGetPixelMapuiv=SDL_GL_GetProcAddress("glGetPixelMapuiv");
	bbglGetPixelMapusv=SDL_GL_GetProcAddress("glGetPixelMapusv");
	bbglGetPointerv=SDL_GL_GetProcAddress("glGetPointerv");
	bbglGetPolygonStipple=SDL_GL_GetProcAddress("glGetPolygonStipple");
	bbglGetString=SDL_GL_GetProcAddress("glGetString");
	bbglGetTexEnvfv=SDL_GL_GetProcAddress("glGetTexEnvfv");
	bbglGetTexEnviv=SDL_GL_GetProcAddress("glGetTexEnviv");
	bbglGetTexGendv=SDL_GL_GetProcAddress("glGetTexGendv");
	bbglGetTexGenfv=SDL_GL_GetProcAddress("glGetTexGenfv");
	bbglGetTexGeniv=SDL_GL_GetProcAddress("glGetTexGeniv");
	bbglGetTexImage=SDL_GL_GetProcAddress("glGetTexImage");
	bbglGetTexLevelParameterfv=SDL_GL_GetProcAddress("glGetTexLevelParameterfv");
	bbglGetTexLevelParameteriv=SDL_GL_GetProcAddress("glGetTexLevelParameteriv");
	bbglGetTexParameterfv=SDL_GL_GetProcAddress("glGetTexParameterfv");
	bbglGetTexParameteriv=SDL_GL_GetProcAddress("glGetTexParameteriv");
	bbglHint=SDL_GL_GetProcAddress("glHint");
	bbglIndexMask=SDL_GL_GetProcAddress("glIndexMask");
	bbglIndexPointer=SDL_GL_GetProcAddress("glIndexPointer");
	bbglIndexd=SDL_GL_GetProcAddress("glIndexd");
	bbglIndexdv=SDL_GL_GetProcAddress("glIndexdv");
	bbglIndexf=SDL_GL_GetProcAddress("glIndexf");
	bbglIndexfv=SDL_GL_GetProcAddress("glIndexfv");
	bbglIndexi=SDL_GL_GetProcAddress("glIndexi");
	bbglIndexiv=SDL_GL_GetProcAddress("glIndexiv");
	bbglIndexs=SDL_GL_GetProcAddress("glIndexs");
	bbglIndexsv=SDL_GL_GetProcAddress("glIndexsv");
	bbglIndexub=SDL_GL_GetProcAddress("glIndexub");
	bbglIndexubv=SDL_GL_GetProcAddress("glIndexubv");
	bbglInitNames=SDL_GL_GetProcAddress("glInitNames");
	bbglInterleavedArrays=SDL_GL_GetProcAddress("glInterleavedArrays");
	bbglIsEnabled=SDL_GL_GetProcAddress("glIsEnabled");
	bbglIsList=SDL_GL_GetProcAddress("glIsList");
	bbglIsTexture=SDL_GL_GetProcAddress("glIsTexture");
	bbglLightModelf=SDL_GL_GetProcAddress("glLightModelf");
	bbglLightModelfv=SDL_GL_GetProcAddress("glLightModelfv");
	bbglLightModeli=SDL_GL_GetProcAddress("glLightModeli");
	bbglLightModeliv=SDL_GL_GetProcAddress("glLightModeliv");
	bbglLightf=SDL_GL_GetProcAddress("glLightf");
	bbglLightfv=SDL_GL_GetProcAddress("glLightfv");
	bbglLighti=SDL_GL_GetProcAddress("glLighti");
	bbglLightiv=SDL_GL_GetProcAddress("glLightiv");
	bbglLineStipple=SDL_GL_GetProcAddress("glLineStipple");
	bbglLineWidth=SDL_GL_GetProcAddress("glLineWidth");
	bbglListBase=SDL_GL_GetProcAddress("glListBase");
	bbglLoadIdentity=SDL_GL_GetProcAddress("glLoadIdentity");
	bbglLoadMatrixd=SDL_GL_GetProcAddress("glLoadMatrixd");
	bbglLoadMatrixf=SDL_GL_GetProcAddress("glLoadMatrixf");
	bbglLoadName=SDL_GL_GetProcAddress("glLoadName");
	bbglLogicOp=SDL_GL_GetProcAddress("glLogicOp");
	bbglMap1d=SDL_GL_GetProcAddress("glMap1d");
	bbglMap1f=SDL_GL_GetProcAddress("glMap1f");
	bbglMap2d=SDL_GL_GetProcAddress("glMap2d");
	bbglMap2f=SDL_GL_GetProcAddress("glMap2f");
	bbglMapGrid1d=SDL_GL_GetProcAddress("glMapGrid1d");
	bbglMapGrid1f=SDL_GL_GetProcAddress("glMapGrid1f");
	bbglMapGrid2d=SDL_GL_GetProcAddress("glMapGrid2d");
	bbglMapGrid2f=SDL_GL_GetProcAddress("glMapGrid2f");
	bbglMaterialf=SDL_GL_GetProcAddress("glMaterialf");
	bbglMaterialfv=SDL_GL_GetProcAddress("glMaterialfv");
	bbglMateriali=SDL_GL_GetProcAddress("glMateriali");
	bbglMaterialiv=SDL_GL_GetProcAddress("glMaterialiv");
	bbglMatrixMode=SDL_GL_GetProcAddress("glMatrixMode");
	bbglMultMatrixd=SDL_GL_GetProcAddress("glMultMatrixd");
	bbglMultMatrixf=SDL_GL_GetProcAddress("glMultMatrixf");
	bbglNewList=SDL_GL_GetProcAddress("glNewList");
	bbglNormal3b=SDL_GL_GetProcAddress("glNormal3b");
	bbglNormal3bv=SDL_GL_GetProcAddress("glNormal3bv");
	bbglNormal3d=SDL_GL_GetProcAddress("glNormal3d");
	bbglNormal3dv=SDL_GL_GetProcAddress("glNormal3dv");
	bbglNormal3f=SDL_GL_GetProcAddress("glNormal3f");
	bbglNormal3fv=SDL_GL_GetProcAddress("glNormal3fv");
	bbglNormal3i=SDL_GL_GetProcAddress("glNormal3i");
	bbglNormal3iv=SDL_GL_GetProcAddress("glNormal3iv");
	bbglNormal3s=SDL_GL_GetProcAddress("glNormal3s");
	bbglNormal3sv=SDL_GL_GetProcAddress("glNormal3sv");
	bbglNormalPointer=SDL_GL_GetProcAddress("glNormalPointer");
	bbglOrtho=SDL_GL_GetProcAddress("glOrtho");
	bbglPassThrough=SDL_GL_GetProcAddress("glPassThrough");
	bbglPixelMapfv=SDL_GL_GetProcAddress("glPixelMapfv");
	bbglPixelMapuiv=SDL_GL_GetProcAddress("glPixelMapuiv");
	bbglPixelMapusv=SDL_GL_GetProcAddress("glPixelMapusv");
	bbglPixelStoref=SDL_GL_GetProcAddress("glPixelStoref");
	bbglPixelStorei=SDL_GL_GetProcAddress("glPixelStorei");
	bbglPixelTransferf=SDL_GL_GetProcAddress("glPixelTransferf");
	bbglPixelTransferi=SDL_GL_GetProcAddress("glPixelTransferi");
	bbglPixelZoom=SDL_GL_GetProcAddress("glPixelZoom");
	bbglPointSize=SDL_GL_GetProcAddress("glPointSize");
	bbglPolygonMode=SDL_GL_GetProcAddress("glPolygonMode");
	bbglPolygonOffset=SDL_GL_GetProcAddress("glPolygonOffset");
	bbglPolygonStipple=SDL_GL_GetProcAddress("glPolygonStipple");
	bbglPopAttrib=SDL_GL_GetProcAddress("glPopAttrib");
	bbglPopClientAttrib=SDL_GL_GetProcAddress("glPopClientAttrib");
	bbglPopMatrix=SDL_GL_GetProcAddress("glPopMatrix");
	bbglPopName=SDL_GL_GetProcAddress("glPopName");
	bbglPrioritizeTextures=SDL_GL_GetProcAddress("glPrioritizeTextures");
	bbglPushAttrib=SDL_GL_GetProcAddress("glPushAttrib");
	bbglPushClientAttrib=SDL_GL_GetProcAddress("glPushClientAttrib");
	bbglPushMatrix=SDL_GL_GetProcAddress("glPushMatrix");
	bbglPushName=SDL_GL_GetProcAddress("glPushName");
	bbglRasterPos2d=SDL_GL_GetProcAddress("glRasterPos2d");
	bbglRasterPos2dv=SDL_GL_GetProcAddress("glRasterPos2dv");
	bbglRasterPos2f=SDL_GL_GetProcAddress("glRasterPos2f");
	bbglRasterPos2fv=SDL_GL_GetProcAddress("glRasterPos2fv");
	bbglRasterPos2i=SDL_GL_GetProcAddress("glRasterPos2i");
	bbglRasterPos2iv=SDL_GL_GetProcAddress("glRasterPos2iv");
	bbglRasterPos2s=SDL_GL_GetProcAddress("glRasterPos2s");
	bbglRasterPos2sv=SDL_GL_GetProcAddress("glRasterPos2sv");
	bbglRasterPos3d=SDL_GL_GetProcAddress("glRasterPos3d");
	bbglRasterPos3dv=SDL_GL_GetProcAddress("glRasterPos3dv");
	bbglRasterPos3f=SDL_GL_GetProcAddress("glRasterPos3f");
	bbglRasterPos3fv=SDL_GL_GetProcAddress("glRasterPos3fv");
	bbglRasterPos3i=SDL_GL_GetProcAddress("glRasterPos3i");
	bbglRasterPos3iv=SDL_GL_GetProcAddress("glRasterPos3iv");
	bbglRasterPos3s=SDL_GL_GetProcAddress("glRasterPos3s");
	bbglRasterPos3sv=SDL_GL_GetProcAddress("glRasterPos3sv");
	bbglRasterPos4d=SDL_GL_GetProcAddress("glRasterPos4d");
	bbglRasterPos4dv=SDL_GL_GetProcAddress("glRasterPos4dv");
	bbglRasterPos4f=SDL_GL_GetProcAddress("glRasterPos4f");
	bbglRasterPos4fv=SDL_GL_GetProcAddress("glRasterPos4fv");
	bbglRasterPos4i=SDL_GL_GetProcAddress("glRasterPos4i");
	bbglRasterPos4iv=SDL_GL_GetProcAddress("glRasterPos4iv");
	bbglRasterPos4s=SDL_GL_GetProcAddress("glRasterPos4s");
	bbglRasterPos4sv=SDL_GL_GetProcAddress("glRasterPos4sv");
	bbglReadBuffer=SDL_GL_GetProcAddress("glReadBuffer");
	bbglReadPixels=SDL_GL_GetProcAddress("glReadPixels");
	bbglRectd=SDL_GL_GetProcAddress("glRectd");
	bbglRectdv=SDL_GL_GetProcAddress("glRectdv");
	bbglRectf=SDL_GL_GetProcAddress("glRectf");
	bbglRectfv=SDL_GL_GetProcAddress("glRectfv");
	bbglRecti=SDL_GL_GetProcAddress("glRecti");
	bbglRectiv=SDL_GL_GetProcAddress("glRectiv");
	bbglRects=SDL_GL_GetProcAddress("glRects");
	bbglRectsv=SDL_GL_GetProcAddress("glRectsv");
	bbglRenderMode=SDL_GL_GetProcAddress("glRenderMode");
	bbglRotated=SDL_GL_GetProcAddress("glRotated");
	bbglRotatef=SDL_GL_GetProcAddress("glRotatef");
	bbglScaled=SDL_GL_GetProcAddress("glScaled");
	bbglScalef=SDL_GL_GetProcAddress("glScalef");
	bbglScissor=SDL_GL_GetProcAddress("glScissor");
	bbglSelectBuffer=SDL_GL_GetProcAddress("glSelectBuffer");
	bbglShadeModel=SDL_GL_GetProcAddress("glShadeModel");
	bbglStencilFunc=SDL_GL_GetProcAddress("glStencilFunc");
	bbglStencilMask=SDL_GL_GetProcAddress("glStencilMask");
	bbglStencilOp=SDL_GL_GetProcAddress("glStencilOp");
	bbglTexCoord1d=SDL_GL_GetProcAddress("glTexCoord1d");
	bbglTexCoord1dv=SDL_GL_GetProcAddress("glTexCoord1dv");
	bbglTexCoord1f=SDL_GL_GetProcAddress("glTexCoord1f");
	bbglTexCoord1fv=SDL_GL_GetProcAddress("glTexCoord1fv");
	bbglTexCoord1i=SDL_GL_GetProcAddress("glTexCoord1i");
	bbglTexCoord1iv=SDL_GL_GetProcAddress("glTexCoord1iv");
	bbglTexCoord1s=SDL_GL_GetProcAddress("glTexCoord1s");
	bbglTexCoord1sv=SDL_GL_GetProcAddress("glTexCoord1sv");
	bbglTexCoord2d=SDL_GL_GetProcAddress("glTexCoord2d");
	bbglTexCoord2dv=SDL_GL_GetProcAddress("glTexCoord2dv");
	bbglTexCoord2f=SDL_GL_GetProcAddress("glTexCoord2f");
	bbglTexCoord2fv=SDL_GL_GetProcAddress("glTexCoord2fv");
	bbglTexCoord2i=SDL_GL_GetProcAddress("glTexCoord2i");
	bbglTexCoord2iv=SDL_GL_GetProcAddress("glTexCoord2iv");
	bbglTexCoord2s=SDL_GL_GetProcAddress("glTexCoord2s");
	bbglTexCoord2sv=SDL_GL_GetProcAddress("glTexCoord2sv");
	bbglTexCoord3d=SDL_GL_GetProcAddress("glTexCoord3d");
	bbglTexCoord3dv=SDL_GL_GetProcAddress("glTexCoord3dv");
	bbglTexCoord3f=SDL_GL_GetProcAddress("glTexCoord3f");
	bbglTexCoord3fv=SDL_GL_GetProcAddress("glTexCoord3fv");
	bbglTexCoord3i=SDL_GL_GetProcAddress("glTexCoord3i");
	bbglTexCoord3iv=SDL_GL_GetProcAddress("glTexCoord3iv");
	bbglTexCoord3s=SDL_GL_GetProcAddress("glTexCoord3s");
	bbglTexCoord3sv=SDL_GL_GetProcAddress("glTexCoord3sv");
	bbglTexCoord4d=SDL_GL_GetProcAddress("glTexCoord4d");
	bbglTexCoord4dv=SDL_GL_GetProcAddress("glTexCoord4dv");
	bbglTexCoord4f=SDL_GL_GetProcAddress("glTexCoord4f");
	bbglTexCoord4fv=SDL_GL_GetProcAddress("glTexCoord4fv");
	bbglTexCoord4i=SDL_GL_GetProcAddress("glTexCoord4i");
	bbglTexCoord4iv=SDL_GL_GetProcAddress("glTexCoord4iv");
	bbglTexCoord4s=SDL_GL_GetProcAddress("glTexCoord4s");
	bbglTexCoord4sv=SDL_GL_GetProcAddress("glTexCoord4sv");
	bbglTexCoordPointer=SDL_GL_GetProcAddress("glTexCoordPointer");
	bbglTexEnvf=SDL_GL_GetProcAddress("glTexEnvf");
	bbglTexEnvfv=SDL_GL_GetProcAddress("glTexEnvfv");
	bbglTexEnvi=SDL_GL_GetProcAddress("glTexEnvi");
	bbglTexEnviv=SDL_GL_GetProcAddress("glTexEnviv");
	bbglTexGend=SDL_GL_GetProcAddress("glTexGend");
	bbglTexGendv=SDL_GL_GetProcAddress("glTexGendv");
	bbglTexGenf=SDL_GL_GetProcAddress("glTexGenf");
	bbglTexGenfv=SDL_GL_GetProcAddress("glTexGenfv");
	bbglTexGeni=SDL_GL_GetProcAddress("glTexGeni");
	bbglTexGeniv=SDL_GL_GetProcAddress("glTexGeniv");
	bbglTexImage1D=SDL_GL_GetProcAddress("glTexImage1D");
	bbglTexImage2D=SDL_GL_GetProcAddress("glTexImage2D");
	bbglTexParameterf=SDL_GL_GetProcAddress("glTexParameterf");
	bbglTexParameterfv=SDL_GL_GetProcAddress("glTexParameterfv");
	bbglTexParameteri=SDL_GL_GetProcAddress("glTexParameteri");
	bbglTexParameteriv=SDL_GL_GetProcAddress("glTexParameteriv");
	bbglTexSubImage1D=SDL_GL_GetProcAddress("glTexSubImage1D");
	bbglTexSubImage2D=SDL_GL_GetProcAddress("glTexSubImage2D");
	bbglTranslated=SDL_GL_GetProcAddress("glTranslated");
	bbglTranslatef=SDL_GL_GetProcAddress("glTranslatef");
	bbglVertex2d=SDL_GL_GetProcAddress("glVertex2d");
	bbglVertex2dv=SDL_GL_GetProcAddress("glVertex2dv");
	bbglVertex2f=SDL_GL_GetProcAddress("glVertex2f");
	bbglVertex2fv=SDL_GL_GetProcAddress("glVertex2fv");
	bbglVertex2i=SDL_GL_GetProcAddress("glVertex2i");
	bbglVertex2iv=SDL_GL_GetProcAddress("glVertex2iv");
	bbglVertex2s=SDL_GL_GetProcAddress("glVertex2s");
	bbglVertex2sv=SDL_GL_GetProcAddress("glVertex2sv");
	bbglVertex3d=SDL_GL_GetProcAddress("glVertex3d");
	bbglVertex3dv=SDL_GL_GetProcAddress("glVertex3dv");
	bbglVertex3f=SDL_GL_GetProcAddress("glVertex3f");
	bbglVertex3fv=SDL_GL_GetProcAddress("glVertex3fv");
	bbglVertex3i=SDL_GL_GetProcAddress("glVertex3i");
	bbglVertex3iv=SDL_GL_GetProcAddress("glVertex3iv");
	bbglVertex3s=SDL_GL_GetProcAddress("glVertex3s");
	bbglVertex3sv=SDL_GL_GetProcAddress("glVertex3sv");
	bbglVertex4d=SDL_GL_GetProcAddress("glVertex4d");
	bbglVertex4dv=SDL_GL_GetProcAddress("glVertex4dv");
	bbglVertex4f=SDL_GL_GetProcAddress("glVertex4f");
	bbglVertex4fv=SDL_GL_GetProcAddress("glVertex4fv");
	bbglVertex4i=SDL_GL_GetProcAddress("glVertex4i");
	bbglVertex4iv=SDL_GL_GetProcAddress("glVertex4iv");
	bbglVertex4s=SDL_GL_GetProcAddress("glVertex4s");
	bbglVertex4sv=SDL_GL_GetProcAddress("glVertex4sv");
	bbglVertexPointer=SDL_GL_GetProcAddress("glVertexPointer");
	bbglViewport=SDL_GL_GetProcAddress("glViewport");
	bbglCopyTexSubImage3D=SDL_GL_GetProcAddress("glCopyTexSubImage3D");
	bbglDrawRangeElements=SDL_GL_GetProcAddress("glDrawRangeElements");
	bbglTexImage3D=SDL_GL_GetProcAddress("glTexImage3D");
	bbglTexSubImage3D=SDL_GL_GetProcAddress("glTexSubImage3D");
	bbglActiveTexture=SDL_GL_GetProcAddress("glActiveTexture");
	bbglClientActiveTexture=SDL_GL_GetProcAddress("glClientActiveTexture");
	bbglCompressedTexImage1D=SDL_GL_GetProcAddress("glCompressedTexImage1D");
	bbglCompressedTexImage2D=SDL_GL_GetProcAddress("glCompressedTexImage2D");
	bbglCompressedTexImage3D=SDL_GL_GetProcAddress("glCompressedTexImage3D");
	bbglCompressedTexSubImage1D=SDL_GL_GetProcAddress("glCompressedTexSubImage1D");
	bbglCompressedTexSubImage2D=SDL_GL_GetProcAddress("glCompressedTexSubImage2D");
	bbglCompressedTexSubImage3D=SDL_GL_GetProcAddress("glCompressedTexSubImage3D");
	bbglGetCompressedTexImage=SDL_GL_GetProcAddress("glGetCompressedTexImage");
	bbglLoadTransposeMatrixd=SDL_GL_GetProcAddress("glLoadTransposeMatrixd");
	bbglLoadTransposeMatrixf=SDL_GL_GetProcAddress("glLoadTransposeMatrixf");
	bbglMultTransposeMatrixd=SDL_GL_GetProcAddress("glMultTransposeMatrixd");
	bbglMultTransposeMatrixf=SDL_GL_GetProcAddress("glMultTransposeMatrixf");
	bbglMultiTexCoord1d=SDL_GL_GetProcAddress("glMultiTexCoord1d");
	bbglMultiTexCoord1dv=SDL_GL_GetProcAddress("glMultiTexCoord1dv");
	bbglMultiTexCoord1f=SDL_GL_GetProcAddress("glMultiTexCoord1f");
	bbglMultiTexCoord1fv=SDL_GL_GetProcAddress("glMultiTexCoord1fv");
	bbglMultiTexCoord1i=SDL_GL_GetProcAddress("glMultiTexCoord1i");
	bbglMultiTexCoord1iv=SDL_GL_GetProcAddress("glMultiTexCoord1iv");
	bbglMultiTexCoord1s=SDL_GL_GetProcAddress("glMultiTexCoord1s");
	bbglMultiTexCoord1sv=SDL_GL_GetProcAddress("glMultiTexCoord1sv");
	bbglMultiTexCoord2d=SDL_GL_GetProcAddress("glMultiTexCoord2d");
	bbglMultiTexCoord2dv=SDL_GL_GetProcAddress("glMultiTexCoord2dv");
	bbglMultiTexCoord2f=SDL_GL_GetProcAddress("glMultiTexCoord2f");
	bbglMultiTexCoord2fv=SDL_GL_GetProcAddress("glMultiTexCoord2fv");
	bbglMultiTexCoord2i=SDL_GL_GetProcAddress("glMultiTexCoord2i");
	bbglMultiTexCoord2iv=SDL_GL_GetProcAddress("glMultiTexCoord2iv");
	bbglMultiTexCoord2s=SDL_GL_GetProcAddress("glMultiTexCoord2s");
	bbglMultiTexCoord2sv=SDL_GL_GetProcAddress("glMultiTexCoord2sv");
	bbglMultiTexCoord3d=SDL_GL_GetProcAddress("glMultiTexCoord3d");
	bbglMultiTexCoord3dv=SDL_GL_GetProcAddress("glMultiTexCoord3dv");
	bbglMultiTexCoord3f=SDL_GL_GetProcAddress("glMultiTexCoord3f");
	bbglMultiTexCoord3fv=SDL_GL_GetProcAddress("glMultiTexCoord3fv");
	bbglMultiTexCoord3i=SDL_GL_GetProcAddress("glMultiTexCoord3i");
	bbglMultiTexCoord3iv=SDL_GL_GetProcAddress("glMultiTexCoord3iv");
	bbglMultiTexCoord3s=SDL_GL_GetProcAddress("glMultiTexCoord3s");
	bbglMultiTexCoord3sv=SDL_GL_GetProcAddress("glMultiTexCoord3sv");
	bbglMultiTexCoord4d=SDL_GL_GetProcAddress("glMultiTexCoord4d");
	bbglMultiTexCoord4dv=SDL_GL_GetProcAddress("glMultiTexCoord4dv");
	bbglMultiTexCoord4f=SDL_GL_GetProcAddress("glMultiTexCoord4f");
	bbglMultiTexCoord4fv=SDL_GL_GetProcAddress("glMultiTexCoord4fv");
	bbglMultiTexCoord4i=SDL_GL_GetProcAddress("glMultiTexCoord4i");
	bbglMultiTexCoord4iv=SDL_GL_GetProcAddress("glMultiTexCoord4iv");
	bbglMultiTexCoord4s=SDL_GL_GetProcAddress("glMultiTexCoord4s");
	bbglMultiTexCoord4sv=SDL_GL_GetProcAddress("glMultiTexCoord4sv");
	bbglSampleCoverage=SDL_GL_GetProcAddress("glSampleCoverage");
	bbglBlendColor=SDL_GL_GetProcAddress("glBlendColor");
	bbglBlendEquation=SDL_GL_GetProcAddress("glBlendEquation");
	bbglBlendFuncSeparate=SDL_GL_GetProcAddress("glBlendFuncSeparate");
	bbglFogCoordPointer=SDL_GL_GetProcAddress("glFogCoordPointer");
	bbglFogCoordd=SDL_GL_GetProcAddress("glFogCoordd");
	bbglFogCoorddv=SDL_GL_GetProcAddress("glFogCoorddv");
	bbglFogCoordf=SDL_GL_GetProcAddress("glFogCoordf");
	bbglFogCoordfv=SDL_GL_GetProcAddress("glFogCoordfv");
	bbglMultiDrawArrays=SDL_GL_GetProcAddress("glMultiDrawArrays");
	bbglMultiDrawElements=SDL_GL_GetProcAddress("glMultiDrawElements");
	bbglPointParameterf=SDL_GL_GetProcAddress("glPointParameterf");
	bbglPointParameterfv=SDL_GL_GetProcAddress("glPointParameterfv");
	bbglPointParameteri=SDL_GL_GetProcAddress("glPointParameteri");
	bbglPointParameteriv=SDL_GL_GetProcAddress("glPointParameteriv");
	bbglSecondaryColor3b=SDL_GL_GetProcAddress("glSecondaryColor3b");
	bbglSecondaryColor3bv=SDL_GL_GetProcAddress("glSecondaryColor3bv");
	bbglSecondaryColor3d=SDL_GL_GetProcAddress("glSecondaryColor3d");
	bbglSecondaryColor3dv=SDL_GL_GetProcAddress("glSecondaryColor3dv");
	bbglSecondaryColor3f=SDL_GL_GetProcAddress("glSecondaryColor3f");
	bbglSecondaryColor3fv=SDL_GL_GetProcAddress("glSecondaryColor3fv");
	bbglSecondaryColor3i=SDL_GL_GetProcAddress("glSecondaryColor3i");
	bbglSecondaryColor3iv=SDL_GL_GetProcAddress("glSecondaryColor3iv");
	bbglSecondaryColor3s=SDL_GL_GetProcAddress("glSecondaryColor3s");
	bbglSecondaryColor3sv=SDL_GL_GetProcAddress("glSecondaryColor3sv");
	bbglSecondaryColor3ub=SDL_GL_GetProcAddress("glSecondaryColor3ub");
	bbglSecondaryColor3ubv=SDL_GL_GetProcAddress("glSecondaryColor3ubv");
	bbglSecondaryColor3ui=SDL_GL_GetProcAddress("glSecondaryColor3ui");
	bbglSecondaryColor3uiv=SDL_GL_GetProcAddress("glSecondaryColor3uiv");
	bbglSecondaryColor3us=SDL_GL_GetProcAddress("glSecondaryColor3us");
	bbglSecondaryColor3usv=SDL_GL_GetProcAddress("glSecondaryColor3usv");
	bbglSecondaryColorPointer=SDL_GL_GetProcAddress("glSecondaryColorPointer");
	bbglWindowPos2d=SDL_GL_GetProcAddress("glWindowPos2d");
	bbglWindowPos2dv=SDL_GL_GetProcAddress("glWindowPos2dv");
	bbglWindowPos2f=SDL_GL_GetProcAddress("glWindowPos2f");
	bbglWindowPos2fv=SDL_GL_GetProcAddress("glWindowPos2fv");
	bbglWindowPos2i=SDL_GL_GetProcAddress("glWindowPos2i");
	bbglWindowPos2iv=SDL_GL_GetProcAddress("glWindowPos2iv");
	bbglWindowPos2s=SDL_GL_GetProcAddress("glWindowPos2s");
	bbglWindowPos2sv=SDL_GL_GetProcAddress("glWindowPos2sv");
	bbglWindowPos3d=SDL_GL_GetProcAddress("glWindowPos3d");
	bbglWindowPos3dv=SDL_GL_GetProcAddress("glWindowPos3dv");
	bbglWindowPos3f=SDL_GL_GetProcAddress("glWindowPos3f");
	bbglWindowPos3fv=SDL_GL_GetProcAddress("glWindowPos3fv");
	bbglWindowPos3i=SDL_GL_GetProcAddress("glWindowPos3i");
	bbglWindowPos3iv=SDL_GL_GetProcAddress("glWindowPos3iv");
	bbglWindowPos3s=SDL_GL_GetProcAddress("glWindowPos3s");
	bbglWindowPos3sv=SDL_GL_GetProcAddress("glWindowPos3sv");
	bbglBeginQuery=SDL_GL_GetProcAddress("glBeginQuery");
	bbglBindBuffer=SDL_GL_GetProcAddress("glBindBuffer");
	bbglBufferData=SDL_GL_GetProcAddress("glBufferData");
	bbglBufferSubData=SDL_GL_GetProcAddress("glBufferSubData");
	bbglDeleteBuffers=SDL_GL_GetProcAddress("glDeleteBuffers");
	bbglDeleteQueries=SDL_GL_GetProcAddress("glDeleteQueries");
	bbglEndQuery=SDL_GL_GetProcAddress("glEndQuery");
	bbglGenBuffers=SDL_GL_GetProcAddress("glGenBuffers");
	bbglGenQueries=SDL_GL_GetProcAddress("glGenQueries");
	bbglGetBufferParameteriv=SDL_GL_GetProcAddress("glGetBufferParameteriv");
	bbglGetBufferPointerv=SDL_GL_GetProcAddress("glGetBufferPointerv");
	bbglGetBufferSubData=SDL_GL_GetProcAddress("glGetBufferSubData");
	bbglGetQueryObjectiv=SDL_GL_GetProcAddress("glGetQueryObjectiv");
	bbglGetQueryObjectuiv=SDL_GL_GetProcAddress("glGetQueryObjectuiv");
	bbglGetQueryiv=SDL_GL_GetProcAddress("glGetQueryiv");
	bbglIsBuffer=SDL_GL_GetProcAddress("glIsBuffer");
	bbglIsQuery=SDL_GL_GetProcAddress("glIsQuery");
	bbglMapBuffer=SDL_GL_GetProcAddress("glMapBuffer");
	bbglUnmapBuffer=SDL_GL_GetProcAddress("glUnmapBuffer");
	bbglAttachShader=SDL_GL_GetProcAddress("glAttachShader");
	bbglBindAttribLocation=SDL_GL_GetProcAddress("glBindAttribLocation");
	bbglBlendEquationSeparate=SDL_GL_GetProcAddress("glBlendEquationSeparate");
	bbglCompileShader=SDL_GL_GetProcAddress("glCompileShader");
	bbglCreateProgram=SDL_GL_GetProcAddress("glCreateProgram");
	bbglCreateShader=SDL_GL_GetProcAddress("glCreateShader");
	bbglDeleteProgram=SDL_GL_GetProcAddress("glDeleteProgram");
	bbglDeleteShader=SDL_GL_GetProcAddress("glDeleteShader");
	bbglDetachShader=SDL_GL_GetProcAddress("glDetachShader");
	bbglDisableVertexAttribArray=SDL_GL_GetProcAddress("glDisableVertexAttribArray");
	bbglDrawBuffers=SDL_GL_GetProcAddress("glDrawBuffers");
	bbglEnableVertexAttribArray=SDL_GL_GetProcAddress("glEnableVertexAttribArray");
	bbglGetActiveAttrib=SDL_GL_GetProcAddress("glGetActiveAttrib");
	bbglGetActiveUniform=SDL_GL_GetProcAddress("glGetActiveUniform");
	bbglGetAttachedShaders=SDL_GL_GetProcAddress("glGetAttachedShaders");
	bbglGetAttribLocation=SDL_GL_GetProcAddress("glGetAttribLocation");
	bbglGetProgramInfoLog=SDL_GL_GetProcAddress("glGetProgramInfoLog");
	bbglGetProgramiv=SDL_GL_GetProcAddress("glGetProgramiv");
	bbglGetShaderInfoLog=SDL_GL_GetProcAddress("glGetShaderInfoLog");
	bbglGetShaderSource=SDL_GL_GetProcAddress("glGetShaderSource");
	bbglGetShaderiv=SDL_GL_GetProcAddress("glGetShaderiv");
	bbglGetUniformLocation=SDL_GL_GetProcAddress("glGetUniformLocation");
	bbglGetUniformfv=SDL_GL_GetProcAddress("glGetUniformfv");
	bbglGetUniformiv=SDL_GL_GetProcAddress("glGetUniformiv");
	bbglGetVertexAttribPointerv=SDL_GL_GetProcAddress("glGetVertexAttribPointerv");
	bbglGetVertexAttribdv=SDL_GL_GetProcAddress("glGetVertexAttribdv");
	bbglGetVertexAttribfv=SDL_GL_GetProcAddress("glGetVertexAttribfv");
	bbglGetVertexAttribiv=SDL_GL_GetProcAddress("glGetVertexAttribiv");
	bbglIsProgram=SDL_GL_GetProcAddress("glIsProgram");
	bbglIsShader=SDL_GL_GetProcAddress("glIsShader");
	bbglLinkProgram=SDL_GL_GetProcAddress("glLinkProgram");
	bbglShaderSource=SDL_GL_GetProcAddress("glShaderSource");
	bbglStencilFuncSeparate=SDL_GL_GetProcAddress("glStencilFuncSeparate");
	bbglStencilMaskSeparate=SDL_GL_GetProcAddress("glStencilMaskSeparate");
	bbglStencilOpSeparate=SDL_GL_GetProcAddress("glStencilOpSeparate");
	bbglUniform1f=SDL_GL_GetProcAddress("glUniform1f");
	bbglUniform1fv=SDL_GL_GetProcAddress("glUniform1fv");
	bbglUniform1i=SDL_GL_GetProcAddress("glUniform1i");
	bbglUniform1iv=SDL_GL_GetProcAddress("glUniform1iv");
	bbglUniform2f=SDL_GL_GetProcAddress("glUniform2f");
	bbglUniform2fv=SDL_GL_GetProcAddress("glUniform2fv");
	bbglUniform2i=SDL_GL_GetProcAddress("glUniform2i");
	bbglUniform2iv=SDL_GL_GetProcAddress("glUniform2iv");
	bbglUniform3f=SDL_GL_GetProcAddress("glUniform3f");
	bbglUniform3fv=SDL_GL_GetProcAddress("glUniform3fv");
	bbglUniform3i=SDL_GL_GetProcAddress("glUniform3i");
	bbglUniform3iv=SDL_GL_GetProcAddress("glUniform3iv");
	bbglUniform4f=SDL_GL_GetProcAddress("glUniform4f");
	bbglUniform4fv=SDL_GL_GetProcAddress("glUniform4fv");
	bbglUniform4i=SDL_GL_GetProcAddress("glUniform4i");
	bbglUniform4iv=SDL_GL_GetProcAddress("glUniform4iv");
	bbglUniformMatrix2fv=SDL_GL_GetProcAddress("glUniformMatrix2fv");
	bbglUniformMatrix3fv=SDL_GL_GetProcAddress("glUniformMatrix3fv");
	bbglUniformMatrix4fv=SDL_GL_GetProcAddress("glUniformMatrix4fv");
	bbglUseProgram=SDL_GL_GetProcAddress("glUseProgram");
	bbglValidateProgram=SDL_GL_GetProcAddress("glValidateProgram");
	bbglVertexAttrib1d=SDL_GL_GetProcAddress("glVertexAttrib1d");
	bbglVertexAttrib1dv=SDL_GL_GetProcAddress("glVertexAttrib1dv");
	bbglVertexAttrib1f=SDL_GL_GetProcAddress("glVertexAttrib1f");
	bbglVertexAttrib1fv=SDL_GL_GetProcAddress("glVertexAttrib1fv");
	bbglVertexAttrib1s=SDL_GL_GetProcAddress("glVertexAttrib1s");
	bbglVertexAttrib1sv=SDL_GL_GetProcAddress("glVertexAttrib1sv");
	bbglVertexAttrib2d=SDL_GL_GetProcAddress("glVertexAttrib2d");
	bbglVertexAttrib2dv=SDL_GL_GetProcAddress("glVertexAttrib2dv");
	bbglVertexAttrib2f=SDL_GL_GetProcAddress("glVertexAttrib2f");
	bbglVertexAttrib2fv=SDL_GL_GetProcAddress("glVertexAttrib2fv");
	bbglVertexAttrib2s=SDL_GL_GetProcAddress("glVertexAttrib2s");
	bbglVertexAttrib2sv=SDL_GL_GetProcAddress("glVertexAttrib2sv");
	bbglVertexAttrib3d=SDL_GL_GetProcAddress("glVertexAttrib3d");
	bbglVertexAttrib3dv=SDL_GL_GetProcAddress("glVertexAttrib3dv");
	bbglVertexAttrib3f=SDL_GL_GetProcAddress("glVertexAttrib3f");
	bbglVertexAttrib3fv=SDL_GL_GetProcAddress("glVertexAttrib3fv");
	bbglVertexAttrib3s=SDL_GL_GetProcAddress("glVertexAttrib3s");
	bbglVertexAttrib3sv=SDL_GL_GetProcAddress("glVertexAttrib3sv");
	bbglVertexAttrib4Nbv=SDL_GL_GetProcAddress("glVertexAttrib4Nbv");
	bbglVertexAttrib4Niv=SDL_GL_GetProcAddress("glVertexAttrib4Niv");
	bbglVertexAttrib4Nsv=SDL_GL_GetProcAddress("glVertexAttrib4Nsv");
	bbglVertexAttrib4Nub=SDL_GL_GetProcAddress("glVertexAttrib4Nub");
	bbglVertexAttrib4Nubv=SDL_GL_GetProcAddress("glVertexAttrib4Nubv");
	bbglVertexAttrib4Nuiv=SDL_GL_GetProcAddress("glVertexAttrib4Nuiv");
	bbglVertexAttrib4Nusv=SDL_GL_GetProcAddress("glVertexAttrib4Nusv");
	bbglVertexAttrib4bv=SDL_GL_GetProcAddress("glVertexAttrib4bv");
	bbglVertexAttrib4d=SDL_GL_GetProcAddress("glVertexAttrib4d");
	bbglVertexAttrib4dv=SDL_GL_GetProcAddress("glVertexAttrib4dv");
	bbglVertexAttrib4f=SDL_GL_GetProcAddress("glVertexAttrib4f");
	bbglVertexAttrib4fv=SDL_GL_GetProcAddress("glVertexAttrib4fv");
	bbglVertexAttrib4iv=SDL_GL_GetProcAddress("glVertexAttrib4iv");
	bbglVertexAttrib4s=SDL_GL_GetProcAddress("glVertexAttrib4s");
	bbglVertexAttrib4sv=SDL_GL_GetProcAddress("glVertexAttrib4sv");
	bbglVertexAttrib4ubv=SDL_GL_GetProcAddress("glVertexAttrib4ubv");
	bbglVertexAttrib4uiv=SDL_GL_GetProcAddress("glVertexAttrib4uiv");
	bbglVertexAttrib4usv=SDL_GL_GetProcAddress("glVertexAttrib4usv");
	bbglVertexAttribPointer=SDL_GL_GetProcAddress("glVertexAttribPointer");
	bbglUniformMatrix2x3fv=SDL_GL_GetProcAddress("glUniformMatrix2x3fv");
	bbglUniformMatrix2x4fv=SDL_GL_GetProcAddress("glUniformMatrix2x4fv");
	bbglUniformMatrix3x2fv=SDL_GL_GetProcAddress("glUniformMatrix3x2fv");
	bbglUniformMatrix3x4fv=SDL_GL_GetProcAddress("glUniformMatrix3x4fv");
	bbglUniformMatrix4x2fv=SDL_GL_GetProcAddress("glUniformMatrix4x2fv");
	bbglUniformMatrix4x3fv=SDL_GL_GetProcAddress("glUniformMatrix4x3fv");
	bbglBindFramebuffer=SDL_GL_GetProcAddress("glBindFramebuffer");
	bbglBindRenderbuffer=SDL_GL_GetProcAddress("glBindRenderbuffer");
	bbglBlitFramebuffer=SDL_GL_GetProcAddress("glBlitFramebuffer");
	bbglCheckFramebufferStatus=SDL_GL_GetProcAddress("glCheckFramebufferStatus");
	bbglDeleteFramebuffers=SDL_GL_GetProcAddress("glDeleteFramebuffers");
	bbglDeleteRenderbuffers=SDL_GL_GetProcAddress("glDeleteRenderbuffers");
	bbglFramebufferRenderbuffer=SDL_GL_GetProcAddress("glFramebufferRenderbuffer");
	bbglFramebufferTexture1D=SDL_GL_GetProcAddress("glFramebufferTexture1D");
	bbglFramebufferTexture2D=SDL_GL_GetProcAddress("glFramebufferTexture2D");
	bbglFramebufferTexture3D=SDL_GL_GetProcAddress("glFramebufferTexture3D");
	bbglFramebufferTextureLayer=SDL_GL_GetProcAddress("glFramebufferTextureLayer");
	bbglGenFramebuffers=SDL_GL_GetProcAddress("glGenFramebuffers");
	bbglGenRenderbuffers=SDL_GL_GetProcAddress("glGenRenderbuffers");
	bbglGenerateMipmap=SDL_GL_GetProcAddress("glGenerateMipmap");
	bbglGetFramebufferAttachmentParameteriv=SDL_GL_GetProcAddress("glGetFramebufferAttachmentParameteriv");
	bbglGetRenderbufferParameteriv=SDL_GL_GetProcAddress("glGetRenderbufferParameteriv");
	bbglIsFramebuffer=SDL_GL_GetProcAddress("glIsFramebuffer");
	bbglIsRenderbuffer=SDL_GL_GetProcAddress("glIsRenderbuffer");
	bbglRenderbufferStorage=SDL_GL_GetProcAddress("glRenderbufferStorage");
	bbglRenderbufferStorageMultisample=SDL_GL_GetProcAddress("glRenderbufferStorageMultisample");

	int profile=0;
	SDL_GL_GetAttribute( SDL_GL_CONTEXT_PROFILE_MASK,&profile );
	BBGL_ES=( profile==SDL_GL_CONTEXT_PROFILE_ES );

	if( BBGL_ES ){
		
		bbglClearDepthf=SDL_GL_GetProcAddress( "glClearDepthf" );
		bbglClearDepth=bbglClearDepthd;
		
		if( BBGL_draw_buffers=SDL_GL_ExtensionSupported( "GL_EXT_draw_buffers" ) ){			//For MRTSs
			
			bbglDrawBuffers=SDL_GL_GetProcAddress( "glDrawBuffersEXT" );
			
		}else if( BBGL_draw_buffers=SDL_GL_ExtensionSupported( "GL_NV_draw_buffers" ) ){	//For MRTs on nvidia shield!
		
			bbglDrawBuffers=SDL_GL_GetProcAddress( "glDrawBuffersNV" );
		}
		
	}else if( bbglDrawBuffers ){
	
		BBGL_draw_buffers=1;
	}

#endif
	
	BBGL_depth_texture=SDL_GL_ExtensionSupported( "GL_EXT_depth_texture" ) || 
		SDL_GL_ExtensionSupported( "GL_ANGLE_depth_texture" ) ||
		SDL_GL_ExtensionSupported( "GL_WEBGL_depth_texture" ) ||
		SDL_GL_ExtensionSupported( "GL_OES_depth_texture" );
	
	BBGL_seamless_cube_map=SDL_GL_ExtensionSupported( "GL_ARB_seamless_cube_map" );
		
	BBGL_texture_filter_anisotropic=SDL_GL_ExtensionSupported( "GL_ARB_texture_filter_anisotropic" ) ||
		SDL_GL_ExtensionSupported( "GL_EXT_texture_filter_anisotropic" );
		
	BBGL_standard_derivatives=!BBGL_ES  || SDL_GL_ExtensionSupported( "GL_OES_standard_derivatives" );
}
